<?php

use App\Extensions\Database\Seeder\SeederTranslation;

class AddSystemCommentsForRgPopup extends SeederTranslation
{
    /* Example ['lang' => ['alias1' => 'value1',...]]*/
    protected array $data = [
        'en' => [
            'RG5.user.comment' => 'RG5 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice that the user have been on a break from gambling. Before the user starts to play, we recommend them to review their limits and to keep their gambling at a safe and fun level.',
            'RG6.user.comment' => 'RG6 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice that the user have been on a break from gambling. Before the user starts to play, we recommend them to review their limits and to keep their gambling at a safe and fun level.',
            'RG8.user.comment' => 'RG8 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice that they spent a lot of time gambling the last few days. We recommended the player to take a break and review their limits and to keep their gambling at a safe and fun level.',
            'RG10.user.comment' => 'RG10 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice that the user have an increased their deposit amounts lately. We recommend the player to review their limits and to keep their gambling at a safe and fun level.',
            'RG11.user.comment' => 'RG11 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice that the user have an increased their number of deposit transactions per day. We recommend the player to review their limits and to keep their gambling at a safe and fun level.',
            'RG12.user.comment' => 'RG12 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice that the user have an increased their deposit amount per transaction today. We recommend the player to review their limits and to keep their gambling at a safe and fun level.',
            'RG13.user.comment' => 'RG13 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice that the user have an increased their deposit amount per transaction during the day. We recommend the player to review their limits and to keep their gambling at a safe and fun level.',
            'RG14.user.comment' => 'RG14 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice that the user had a big win. We congratulated the user but also inform them that we recommend taking a break after such an incredible win. We also recommended the player to review their limits and to keep their gambling at a safe and fun level.',
            'RG19.user.comment' => 'RG19 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice that the user have spent quite a lot on gambling this month. We recommend the player to take a break but also to review their limits and to keep their gambling at a safe and fun level.',
            'RG20.user.comment' => 'RG20 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice that the user have spent quite a lot on gambling this month. We recommend the player to take a break but also to review their limits and to keep their gambling at a safe and fun level.',
            'RG21.user.comment' => 'RG21 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice that the user has updated their loss limit. We recommend the player to take a break and to keep their gambling at a safe and fun level.',
            'RG28.user.comment' => 'RG28 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice a change in the player’s gambling pattern, an increase in bet level. We recommend the player to user our tool Max Bet protection and also to review their other limits and to keep their gambling at a safe and fun level.',
            'RG29.user.comment' => 'RG29 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice a change in the player’s gambling pattern, an increase in bet level. We recommend the player to user our tool Max Bet protection and also to review their other limits and to keep their gambling at a safe and fun level.',
            'RG30.user.comment' => 'RG30 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice a change in the player’s gambling pattern, the amount of wager per day has increased from previous days. We recommend the player to review their limits and to keep their gambling at a safe and fun level.',
            'RG31.user.comment' => 'RG31 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice a change in the player’s gambling pattern, the amount of wager per day have increased from previous days. We recommend the player to review their limits and to keep their gambling at a safe and fun level.',
            'RG32.user.comment' => 'RG32 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice an increase in the time spent gambling. We recommend the player to take a break but also to review their limits and to keep their gambling at a safe and fun level.',
            'RG33.user.comment' => 'RG33 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice an increase in time spent their average unique game session . We recommend the player to take a break but also to review their limits and to keep their gambling at a safe and fun level.',
            'RG34.user.comment' => 'RG34 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice an increase in game sessions during the current day. We recommend the player to take a break but also to review their limits and to keep their gambling at a safe and fun level.',
            'RG35.user.comment' => 'RG35 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice an increase an increase in the average bet from previous game sessions. We recommend the player to decrease their bet size but also to use our tool Max Bet protection. We also advised the player to review their limits and to keep their gambling at a safe and fun level.',
            'RG38.user.comment' => 'RG38 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice that the user have spent quite a lot on gambling this month. We recommend the player to take a break but also advice the player to urgently review their limits and to keep their gambling at a safe and fun level.',
            'RG39.user.comment' => 'RG39 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice that the user have spent quite a lot on gambling this month. We recommend the player to take a break but also advised the player to urgently review their limits and to keep their gambling at a safe and fun level.',
            'RG59.user.comment' => 'RG59 Flag was triggered. User have a risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice that the player are gambling quite late at night. We advised the player to go to bed as most people are sleeping. We also recommend the player to review their limits and to keep their gambling at a safe and fun level.',
            'RG68.user.comment' => 'RG68 Flag was triggered. User has risk {{tag}}. An interaction via popup in gameplay was made to inform customer that we notice an increase in activity on the account and recommend him to review his limits and to keep his gambling at a safe and fun level.'
        ]
    ];
}
